import "./globals.css";
import { Providers } from "./clientProvider";
import { Mulish } from 'next/font/google';

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  fallback: ['Arial', 'sans-serif'], // Specify fallback fonts
});
export const metadata = {
  title: "Raw Material Management Tool",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className} suppressHydrationWarning>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
