"use client";
import { motion } from "framer-motion";
import { useState, useEffect } from "react";
import SearchDropdown from "../Input/SearchDropdown";
import ManualEntryComponent from "./ManualEntryComponent";
import TableActionDropdown from "../common/TableActionDropdown";
import { getData } from "@/api/API";

export default function SheetComponent({
  items = [],
  onDelete,
  setterFunction,
  poSearched,
  poNumber
}) {
  const [showManualEntry, setShowManualEntry] = useState(false);
  const [quantities, setQuantities] = useState({});
  const [units, setUnits] = useState([]);
  const [defaultUnits, setDefaultUnits] = useState({
    number: "",
    weight: "",
    distance: ""
  });

  const handleManualEntry = (formData) => {
    // Generate a unique ID for manual entries, or use the existing material's ID if available
    const isAutoGenerated = !formData.existingRawMaterialId;
    const itemId = formData.existingRawMaterialId 
      ? formData.existingRawMaterialId  // Use the existing material's ID
      : `m_${Date.now() % 10000}${Math.floor(Math.random() * 1000)}`; // Generate a simple numeric ID for new materials
    
    const newItem = {
      ...formData,
      po_item_list_id: itemId,
      isAutoGeneratedId: isAutoGenerated, // Add this flag
      remaining_quantity: formData.quantity_requested,
      po_quantity: formData.quantity_requested,
      po_number: poNumber,
      history_date: formData.history_date,
    };
  
    setterFunction((prev) => [...prev, newItem]);
    setShowManualEntry(false);
  };


  // Add this useEffect to fetch units when component mounts
  useEffect(() => {
    const fetchUnits = async () => {
      const response = await getData("/master/units/");
      setUnits(response.data);
      
      // Find default units
      if (response.data && response.data.length > 0) {
        const numberUnit = response.data.find(unit => unit.type === "NUMBER" && unit.name.toLowerCase() === "numbers");
        const weightUnit = response.data.find(unit => unit.type === "WEIGHT" && unit.name.toLowerCase() === "kilograms");
        const distanceUnit = response.data.find(unit => unit.type === "DISTANCE" && unit.name.toLowerCase() === "millimetre");
        
        setDefaultUnits({
          number: numberUnit ? numberUnit.id : "",
          weight: weightUnit ? weightUnit.id : "",
          distance: distanceUnit ? distanceUnit.id : ""
        });
        
        // Apply default units to existing items that don't have units set
        if (items.length > 0) {
          const updatedItems = items.map(item => {
            const updates = {};
            
            if (!item.quantity_requested_unit_id && numberUnit) {
              updates.quantity_requested_unit_id = numberUnit.id;
            }
            
            if (!item.weight_requested_unit_id && weightUnit) {
              updates.weight_requested_unit_id = weightUnit.id;
            }
            
            if (!item.thickness_unit_id && distanceUnit) {
              updates.thickness_unit_id = distanceUnit.id;
            }
            
            if (!item.blank_size_unit_id && distanceUnit) {
              updates.blank_size_unit_id = distanceUnit.id;
            }
            
            if (!item.slit_size_unit_id && distanceUnit) {
              updates.slit_size_unit_id = distanceUnit.id;
            }
            
            return { ...item, ...updates };
          });
          
          setterFunction(updatedItems);
        }
      }
    };
    fetchUnits();
  }, []);

  const getUnitsByType = (type) => {
    return units.filter((unit) => unit.type === type);
  };
  const handleThicknessChange = (POItemId, newValue) => {
    if (newValue < 0) return;
    const updatedItems = items.map((item) => {
      if (item.po_item_list_id === POItemId) {
        return {
          ...item,
          thickness: Math.max(0, newValue),
        };
      }
      return item;
    });
    setterFunction(updatedItems);
  };

  const handleSlitSizeChange = (POItemId, newValue) => {
    if (newValue < 0) return;
    const updatedItems = items.map((item) => {
      if (item.po_item_list_id === POItemId) {
        return {
          ...item,
          slit_size: Math.max(0, newValue),
        };
      }
      return item;
    });
    setterFunction(updatedItems);
  };

  const handleQuantityChange = (POItemId, newValue) => {
    if (newValue < 0) return;
    
    const updatedItems = items.map((item) => {
      if (item.po_item_list_id === POItemId) {
        const newQuantity = Math.min(parseFloat(newValue), item.remaining_quantity);
        
        // Calculate new weight based on dimensions and quantity
        let newWeight = item.weight;
        if (item.thickness && item.blank_size && item.slit_size) {
          // Convert mm to m³
          const blankSize = parseFloat(item.blank_size) / 1000;
          const slitSize = parseFloat(item.slit_size) / 1000;
          const thickness = parseFloat(item.thickness) / 1000;
          
          // Calculate volume in m³
          const volume = blankSize * slitSize * thickness;
          
          // Calculate weight in kg (density of steel is approximately 7865 kg/m³)
          const weightKg = volume * 7865 * newQuantity;
          
          // Get the selected weight unit
          const selectedUnit = units.find(u => u.id === parseInt(item.weight_requested_unit_id));
          const unitType = selectedUnit?.symbol === 'T' ? 'TONNES' : 'KG';
          
          // Convert to tonnes if needed and round to 6 decimal places
          newWeight = unitType === 'TONNES' ? parseFloat((weightKg / 1000).toFixed(6)) : parseFloat(weightKg.toFixed(6));
        }
        
        return {
          ...item,
          quantity_requested: newQuantity,
          weight: newWeight
        };
      }
      return item;
    });
    setterFunction(updatedItems);
  };
  const handleWeightChange = (POItemId, newValue) => {
    if (newValue < 0) return;
    
    const updatedItems = items.map((item) => {
      if (item.po_item_list_id === POItemId) {
        const newWeight = Math.max(0, parseFloat(newValue));
        
        // Comment out the quantity calculation from weight
        /*
        // Calculate new quantity based on dimensions and weight
        let newQuantity = item.quantity_requested;
        if (item.thickness && item.blank_size && item.slit_size) {
          // Convert mm to m³
          const blankSize = parseFloat(item.blank_size) / 1000;
          const slitSize = parseFloat(item.slit_size) / 1000;
          const thickness = parseFloat(item.thickness) / 1000;
          
          // Calculate volume in m³
          const volume = blankSize * slitSize * thickness;
          
          // Get the selected weight unit
          const selectedUnit = units.find(u => u.id === parseInt(item.weight_requested_unit_id));
          const unitType = selectedUnit?.symbol === 'T' ? 'TONNES' : 'KG';
          
          // Convert to kg if in tonnes
          const weightKg = unitType === 'TONNES' ? newWeight * 1000 : newWeight;
          
          // Calculate quantity and round to 6 decimal places
          newQuantity = parseFloat((weightKg / (volume * 7865)).toFixed(6));
          
          // Ensure quantity doesn't exceed remaining quantity
          newQuantity = Math.min(newQuantity, item.remaining_quantity);
        }
        */
        
        return {
          ...item,
          weight: newWeight,
          // Remove the quantity update
          // quantity_requested: newQuantity
        };
      }
      return item;
    });
    setterFunction(updatedItems);
  };
  

  const handleMaterialSelect = (selected, index, setProperty) => {
    setterFunction((prev) =>
      prev.map((item, i) => {
        if (i === index) {
          return {
            ...item,
            [setProperty]: selected.value,
          };
        }
        return item;
      })
    );
  };

  console.log(items);

  const handleBlankSizeChange = (POItemId, newValue) => {
    if (newValue < 0) return;
    const updatedItems = items.map((item) => {
      if (item.po_item_list_id === POItemId) {
        return {
          ...item,
          blank_size: Math.max(0, newValue),
        };
      }
      return item;
    });
    setterFunction(updatedItems);
  };


  const headers = [
    "Existing Raw Material",
    "Name",
    "Description",
    "Quantity",
    "Remaining Quantity",
    "Set Quantity",
    "Blank Size",
    "Weight",
    "Thickness",
    "Slit Size",
    "Unit Price",
    "Tax %",
    "Delivery Date",
    "History Date",
    "Coil",
    "Actions",
  ];

  const handleDelete = (item) => {
    // Make sure we're identifying items uniquely
    if (!item.po_item_list_id) {
      // If the item doesn't have a po_item_list_id, generate a temporary one
      // This is important for manually added items that might not have this ID
      item = { ...item, po_item_list_id: `temp_${Date.now()}_${Math.random().toString(36).substr(2, 9)}` };
    }
    
    // Call the parent component's onDelete function with the item
    onDelete(item);
  };
  return (
    <>
      {showManualEntry && (
        <div className="mb-6">
          <ManualEntryComponent 
      onSubmit={handleManualEntry} 
      poNumber={poNumber} // Add this line
    />
        </div>
      )}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white rounded-xl shadow-xl p-6"
      >
        {poSearched && (
          <div className="mb-4">
            <button
              onClick={() => setShowManualEntry((prev) => !prev)}
              className="px-4 py-2 bg-gradient-to-r from-amber-500 to-amber-600 text-white rounded-lg hover:from-amber-600 hover:to-amber-700 flex items-center gap-2"
            >
              <svg
                className="w-5 h-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 4v16m8-8H4"
                />
              </svg>
              Add Sheet Manually
            </button>
          </div>
        )}
        <div className="overflow-x-auto rounded-lg border border-gray-200">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gradient-to-r from-amber-50 to-amber-100">
              <tr>
                {headers.map((header, index) => (
                  <th
                    key={index}
                    className="px-3 py-2 text-left text-xs font-semibold text-gray-700 tracking-wider whitespace-nowrap"
                  >
                    {header}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-100">
              {Array.isArray(items) && items.length > 0 ? (
                items.map((item, index) => {
                  const currentQuantity = quantities[item.name] || 0;
                  const remainingQuantity = item.remaining_quantity;

                  const rowData = [
                    item.name,
                    item.description,
                    item.po_quantity,
                    remainingQuantity,
                    item.quantity_requested || 0,
                    item.blank_size,
                    item.weight || "",
                    item.thickness || "",
                    item.slit_size || "",
                    item.unit_price,
                    `${item.tax_percent}%`,
                    item.expected_delivery_date,
                    item.history_date,
                  ];

                  return (
                    <tr
                      key={index}
                      className="hover:bg-amber-50 transition-all duration-200"
                    >
                      <td className="px-3 py-2">
                        <SearchDropdown
                          searchEndpoint="/inventory/search/raw_materials/?q=&is_dropdown=true"
                          onSelect={(selected) =>
                            handleMaterialSelect(
                              selected,
                              index,
                              "existingRawMaterialId"
                            )
                          }
                          placeholder="Search materials..."
                          displayField="item_name"
                          valueField="id"
                          className="min-w-[150px] text-xs"
                       
                          resultsPath="data.results" // Add this to specify the path to the results array
                        />
                      </td>
                      {rowData.map((data, idx) => (
                        <td
                          key={idx}
                          className="px-3 py-2 text-xs text-gray-700 whitespace-nowrap"
                        >
                          {idx === 4 ? (
                            <div className="flex items-center gap-1">
                              <input
                                type="number"
                                min="0"
                                value={item.quantity_requested}
                                onChange={(e) =>
                                  handleQuantityChange(
                                    item.po_item_list_id,
                                    e.target.value
                                  )
                                }
                                max={item.po_quantity}
                                className="w-16 px-2 py-1 border border-gray-300 rounded-lg focus:ring-1 focus:ring-amber-500 focus:border-amber-500 text-xs"
                              />
                              <select
                                value={item.quantity_requested_unit_id || ""}
                                onChange={(e) =>
                                  handleMaterialSelect(
                                    { value: e.target.value },
                                    index,
                                    "quantity_requested_unit_id"
                                  )
                                }
                                className="w-16 px-1 py-1 border border-gray-300 rounded-lg focus:ring-1 focus:ring-amber-500 focus:border-amber-500 text-xs"
                              >
                                <option value="">Unit</option>
                                {getUnitsByType("NUMBER").map((unit) => (
                                  <option key={unit.id} value={unit.id}>
                                    {unit.name}
                                  </option>
                                ))}
                              </select>
                            </div>
                          ) : idx === 6 ? (
                            <div className="flex items-center gap-1">
                              <input
                                type="number"
                                min="0"
                                value={item.weight || ""}
                                onChange={(e) =>
                                  handleWeightChange(
                                    item.po_item_list_id,
                                    e.target.value
                                  )
                                }
                                className="w-16 px-2 py-1 border border-gray-300 rounded-lg focus:ring-1 focus:ring-amber-500 focus:border-amber-500 text-xs"
                              />
                              <select
                                value={item.weight_requested_unit_id || ""}
                                onChange={(e) =>
                                  handleMaterialSelect(
                                    { value: e.target.value },
                                    index,
                                    "weight_requested_unit_id"
                                  )
                                }
                                className="w-16 px-1 py-1 border border-gray-300 rounded-lg focus:ring-1 focus:ring-amber-500 focus:border-amber-500 text-xs"
                              >
                                <option value="">Unit</option>
                                {getUnitsByType("WEIGHT").map((unit) => (
                                  <option key={unit.id} value={unit.id}>
                                    {unit.name}
                                  </option>
                                ))}
                              </select>
                            </div>
                          ) : idx === 7 ? (
                            <div className="flex items-center gap-1">
                              <input
                                type="number"
                                min="0"
                                value={item.thickness || ""}
                                onChange={(e) =>
                                  handleThicknessChange(
                                    item.po_item_list_id,
                                    e.target.value
                                  )
                                }
                                className="w-16 px-2 py-1 border border-gray-300 rounded-lg focus:ring-1 focus:ring-amber-500 focus:border-amber-500 text-xs"
                              />
                              <select
                                value={item.thickness_unit_id || ""}
                                onChange={(e) =>
                                  handleMaterialSelect(
                                    { value: e.target.value },
                                    index,
                                    "thickness_unit_id"
                                  )
                                }
                                className="w-16 px-1 py-1 border border-gray-300 rounded-lg focus:ring-1 focus:ring-amber-500 focus:border-amber-500 text-xs"
                              >
                                <option value="">Unit</option>
                                {getUnitsByType("DISTANCE").map((unit) => (
                                  <option key={unit.id} value={unit.id}>
                                    {unit.name}
                                  </option>
                                ))}
                              </select>
                            </div>
                          ) : idx === 5 ? (
                            <div className="flex items-center gap-1">
                              <input
                                type="number"
                                min="0"
                                value={item.blank_size || ""}
                                onChange={(e) =>
                                  handleBlankSizeChange(
                                    item.po_item_list_id,
                                    e.target.value
                                  )
                                }
                                className="w-16 px-2 py-1 border border-gray-300 rounded-lg focus:ring-1 focus:ring-amber-500 focus:border-amber-500 text-xs"
                              />
                              <select
                                value={item.blank_size_unit_id || ""}
                                onChange={(e) =>
                                  handleMaterialSelect(
                                    { value: e.target.value },
                                    index,
                                    "blank_size_unit_id"
                                  )
                                }
                                className="w-16 px-1 py-1 border border-gray-300 rounded-lg focus:ring-1 focus:ring-amber-500 focus:border-amber-500 text-xs"
                              >
                                <option value="">Unit</option>
                                {getUnitsByType("DISTANCE").map((unit) => (
                                  <option key={unit.id} value={unit.id}>
                                    {unit.name}
                                  </option>
                                ))}
                              </select>
                            </div>
                          ) : idx === 8 ? (
                            <div className="flex items-center gap-1">
                              <input
                                type="number"
                                min="0"
                                value={item.slit_size || ""}
                                onChange={(e) =>
                                  handleSlitSizeChange(
                                    item.po_item_list_id,
                                    e.target.value
                                  )
                                }
                                className="w-16 px-2 py-1 border border-gray-300 rounded-lg focus:ring-1 focus:ring-amber-500 focus:border-amber-500 text-xs"
                              />
                              <select
                                value={item.slit_size_unit_id || ""}
                                onChange={(e) =>
                                  handleMaterialSelect(
                                    { value: e.target.value },
                                    index,
                                    "slit_size_unit_id"
                                  )
                                }
                                className="w-16 px-1 py-1 border border-gray-300 rounded-lg focus:ring-1 focus:ring-amber-500 focus:border-amber-500 text-xs"
                              >
                                <option value="">Unit</option>
                                {getUnitsByType("DISTANCE").map((unit) => (
                                  <option key={unit.id} value={unit.id}>
                                    {unit.name}
                                  </option>
                                ))}
                              </select>
                            </div>
                          ) : (
                            data
                          )}
                        </td>
                      ))}

                      <td className="px-3 py-2">
                     
                   
                      <SearchDropdown
                          searchEndpoint="/inventory/search/coils/?q=&is_dropdown=true"
                          onSelect={(selected) =>
                            handleMaterialSelect(
                              selected,
                              index,
                              "existingRawMaterialId"
                            )
                          }
                          placeholder="Search materials..."
                          displayField="item_name"
                          valueField="id"
                          className="min-w-[150px] text-xs"
                        />
                      </td>
                      <td className="px-3 py-2">
                        <div className="flex items-center gap-1">
                          <button
                            onClick={() => handleDelete(item)}
                            className="p-1 bg-gradient-to-r from-red-500 to-red-600 rounded-lg hover:from-red-600 hover:to-red-700 transition-all duration-200"
                            title="Delete"
                          >
                            <svg
                              className="w-3 h-3 text-white"
                              fill="none"
                              viewBox="0 0 24 24"
                              stroke="currentColor"
                            >
                              <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth={2}
                                d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                              />
                            </svg>
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              ) : (
                <tr>
                  <td
                    colSpan={headers.length}
                    className="px-3 py-6 text-center text-gray-500 bg-gray-50 text-xs"
                  >
                    No items found
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </motion.div>
    </>
  );
}
